//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUCHANGEntities.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int ID { get; set; }
        public string AUTHOR { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> SORT { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public Nullable<bool> DISABLED_BAK { get; set; }
        public Nullable<System.DateTime> BUD_DT { get; set; }
        public Nullable<int> BUD_USR_ID { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
        public Nullable<int> UPD_USR_ID { get; set; }
    }
}
